# Generated by Django 6.0.5 on 2026-07-19 06:28

from django.db import migrations, models


def update_initial_puzzles(apps, schema_editor):
    ChessPuzzle = apps.get_model('game', 'ChessPuzzle')
    updates = {
        "Daily Puzzle #1": {"rating": 1200, "tags": "Mate in 2"},
        "Daily Puzzle #2": {"rating": 1000, "tags": "Mate in 1"},
        "Daily Puzzle #3": {"rating": 1100, "tags": "Endgame"},
        "Daily Puzzle #4": {"rating": 1600, "tags": "Fork,Tactics"},
        "Daily Puzzle #5": {"rating": 1500, "tags": "Pin,Tactics"},
        "Daily Puzzle #6": {"rating": 1800, "tags": "Mate in 2,Tactics"},
        "Daily Puzzle #7": {"rating": 900, "tags": "Mate in 1,Endgame"},
    }
    for title, values in updates.items():
        ChessPuzzle.objects.filter(title=title).update(rating=values["rating"], tags=values["tags"])


def reverse_update_initial_puzzles(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0038_alter_activegame_game_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='chesspuzzle',
            name='rating',
            field=models.IntegerField(db_index=True, default=1500),
        ),
        migrations.AddField(
            model_name='chesspuzzle',
            name='tags',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.RunPython(update_initial_puzzles, reverse_update_initial_puzzles),
    ]
