# Generated by Django 6.0.5 on 2026-07-19 06:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0039_chesspuzzle_rating_chesspuzzle_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chesspuzzle',
            name='rating',
            field=models.IntegerField(db_index=True, default=1500, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3000)]),
        ),
        migrations.AlterField(
            model_name='chesspuzzle',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
